#!/usr/bin/env python3
"""
Build the page's test fixture using the scraper's OWN payload builder.

Why this exists: the first version of this fixture was hand-written to
match what I believed latest.json looked like. It carried `length` and
`matter` as separate fields. The real payload carries neither, only a
single `category` string. Forty-three render tests passed against a page
that dropped all fifteen trial lists in production.

A fixture that is written by hand is a second, unverified specification
of the payload. This one is generated by build_state and build_latest,
so it is the same shape by construction.

Usage:  python make_fixture.py <dir-of-real-pdfs> [out.json]
"""

import json
import os
import shutil
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import scrape

# Where to find the court's index page. Checked in order, so this
# works both locally and in the sandbox it was written in.
INDEX_CANDIDATES = [
    "bc-index.html",
    os.path.join("data", "bc-index.html"),
    "/mnt/user-data/uploads/bc-index.html",
]


def find_index():
    for p in INDEX_CANDIDATES:
        if os.path.exists(p):
            return p
    return None


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "data/raw"
    out = sys.argv[2] if len(sys.argv) > 2 else "sample_latest.json"
    out = os.path.abspath(out)
    index_path = sys.argv[3] if len(sys.argv) > 3 else find_index()

    if not os.path.isdir(src):
        print("No such directory: %s" % src)
        return 1
    if not index_path or not os.path.exists(index_path):
        print("Cannot find the court's index HTML. Looked for:")
        for p in INDEX_CANDIDATES:
            print("   %s" % p)
        print()
        print("Download it with:")
        print("  curl.exe -s https://www.bccourts.ca/supreme_court/"
              "scheduling/index.aspx -o bc-index.html")
        return 1

    src = os.path.abspath(src)
    index_path = os.path.abspath(index_path)
    html = open(index_path, encoding="utf-8", errors="replace").read()

    tmp = tempfile.mkdtemp(prefix="vcdfix-")
    os.chdir(tmp)
    scrape.ensure_dirs()

    # Copy the archived PDFs in so parse_document can read them.
    for root, _d, files in os.walk(src):
        for fn in files:
            if not fn.lower().endswith(".pdf"):
                continue
            d = os.path.join(scrape.RAW, fn[:2])
            os.makedirs(d, exist_ok=True)
            shutil.copy(os.path.join(root, fn), os.path.join(d, fn))

    docs = scrape.collect_links(html, scrape.INDEX_URL)
    print("%d documents from the index" % len(docs))

    # Map each link to its archived copy by slug.
    on_disk = {}
    for root, _d, files in os.walk(scrape.RAW):
        for fn in files:
            m = fn.rsplit(".", 1)[0]
            if "-" in m:
                on_disk[m.split("-", 1)[1]] = os.path.join(root, fn)

    records = []
    for doc in docs:
        slug = scrape.slugify(doc["title"])
        path = on_disk.get(slug)
        if not path:
            print("  no archived copy for %s" % doc["title"])
            continue
        with open(path, "rb") as f:
            content = f.read()
        text = scrape.extract_text(content, doc["kind"])
        rec = {
            "title": doc["title"], "url": doc["url"], "kind": doc["kind"],
            "is_instruction": doc["is_instruction"],
            "checked_at": scrape.iso(scrape.now()),
            "status": "FIRST_SEEN", "http_status": 200,
            "bytes_hash": scrape.sha256(content),
            "text_hash": (scrape.sha256(text.encode("utf-8"))
                          if text is not None else None),
            "size_bytes": len(content),
            "last_modified": "Tue, 28 Jul 2026 17:04:21 GMT",
            "etag": '"%s:0"' % slug[:12],
            "readable": text is not None, "note": None,
            "archive_path": path,
        }
        if not doc["is_instruction"]:
            rec["parse"] = scrape.parse_document(rec, doc, None)
        records.append(rec)

    state = scrape.build_state(records, {}, "fixture")
    payload = scrape.build_latest(state, records, "fixture", [], [], True)

    with open(out, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=1, sort_keys=True)

    keys = sorted(payload["documents"][0].keys())
    print()
    print("wrote %s" % out)
    print("documents: %d" % len(payload["documents"]))
    print("fields per document: %s" % ", ".join(keys))
    trials = [d for d in payload["documents"]
              if d.get("category") and
              d["category"].split(",")[0].strip() in
              ("2 Days", "3 Days", "4-5 Days", "6-15 Days", "16+ Days")]
    print("trial lists: %d" % len(trials))
    print("instruction docs: %d"
          % sum(1 for d in payload["documents"] if d["is_instruction"]))
    print("empty lists: %d"
          % sum(1 for d in payload["documents"]
                if not d["is_instruction"] and not d.get("dates")))
    return 0


if __name__ == "__main__":
    sys.exit(main())
