#!/usr/bin/env python3
"""
Regression tests for the Vancouver parser and grid.

Pinned to the real documents generated by the court at 17:03 Pacific on
2026-07-27. If the court changes its template these will fail, which is
the point: a silent template change is the failure mode that produces
confidently wrong dates.

Usage:  python test_parse.py [path-to-pdf-directory]
"""

import os
import sys
from datetime import date

import parse
import grid

DEFAULT_DIR = os.path.join("data", "raw")
AS_AT = date(2026, 7, 28)

PASS, FAIL = [], []


def check(label, got, want):
    if got == want:
        PASS.append(label)
        print("  ok    %s" % label)
    else:
        FAIL.append(label)
        print("  FAIL  %s: got %r, want %r" % (label, got, want))


def find(root, fragment):
    for r, _d, files in os.walk(root):
        for fn in files:
            if fragment in fn.lower() and fn.lower().endswith(".pdf"):
                return os.path.join(r, fn)
    return None


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_DIR
    if not os.path.isdir(root):
        print("No such directory: %s" % root)
        return 1

    # -- envelope and both date formats -----------------------------
    print("envelope and date formats")
    r = parse.parse_file(find(root, "2-day-civil-trials"))
    check("format A parses", r.status, "PARSED")
    check("category split", (r.length, r.matter), ("2 Days", "Civil"))
    check("court timestamp read", r.date_created, "2026-07-27T17:03")
    check("ISO output", r.earliest, "2027-03-22")
    check("multi-page total", len(r.slots), 90)

    r = parse.parse_file(find(root, "trial-management"))
    check("format B parses", r.status, "PARSED")
    check("format B ISO", r.earliest, "2026-08-04")

    # -- the page-boundary bug --------------------------------------
    print("\ncontinuation pages")
    r = parse.parse_file(find(root, "2-day-mva-trials"))
    check("6-page document fully read", r.pages, 6)
    check("all dates across all pages", len(r.slots), 188)

    # -- date carry-forward -----------------------------------------
    print("\ndate carry-forward")
    r = parse.parse_file(find(root, "pre-trial-conference"))
    check("slots exceed distinct dates", len(r.slots) > len(r.dates), True)
    check("slot count", len(r.slots), 213)
    check("distinct dates", len(r.dates), 113)
    check("no slot lacks a date",
          all(s["date"] for s in r.slots), True)

    # -- AM/PM columns ----------------------------------------------
    print("\nAM and PM columns")
    r = parse.parse_file(find(root, "sca-available"))
    both = [d for d in r.dates
            if len(set(s["period"] for s in r.slots
                       if s["date"] == d)) == 2]
    check("one date can hold both am and pm slots", len(both) > 0, True)
    first = [s for s in r.slots if s["date"] == "2026-08-05"]
    check("am slot duration", [s["duration"] for s in first
                               if s["period"] == "am"], ["1 hour 30 minutes"])
    check("pm slot duration", [s["duration"] for s in first
                               if s["period"] == "pm"], ["2 hour"])

    r = parse.parse_file(find(root, "bankruptcy"))
    check("column is the only period signal when no time is printed",
          sorted(set(s["period"] for s in r.slots)), ["am"])

    r = parse.parse_file(find(root, "registrar-available"))
    check("explicit time converted to 24h",
          [s["time"] for s in r.slots
           if s["date"] == "2026-08-05"][:1], ["14:00"])

    # -- annotations -------------------------------------------------
    print("\nper-date qualifiers")
    r = parse.parse_file(find(root, "4-5-day-civil"))
    check("qualifier captured",
          sorted(set(s["note"] for s in r.slots if s["note"])),
          ["4 day hearings only"])
    check("qualified count", len([s for s in r.slots if s["note"]]), 3)

    # -- no dates versus unreadable ----------------------------------
    print("\nempty versus unreadable")
    r = parse.parse_file(find(root, "6-15-day-civil"))
    check("empty list is NO_DATES, not UNREADABLE", r.status, "NO_DATES")
    check("envelope still parsed", r.length, "6-15 Days")

    r = parse.parse_file(find(root, "settlement-conference"))
    check("structurally unavailable category", r.status, "NO_DATES")
    check("empty category preserved, not invented", r.matter, None)

    r = parse.parse_file(find(root, "booking-trials"))
    check("instruction doc has no envelope", r.status, "UNREADABLE")

    check("garbage is unreadable, never NO_DATES",
          parse.parse_pdf(b"not a pdf at all").status, "UNREADABLE")

    # -- wrong document served ---------------------------------------
    print("\nvalidation against the request")
    r = parse.parse_file(find(root, "2-day-civil-trials"),
                         expect_location="Victoria")
    check("body checked against the location asked for",
          r.status, "UNREADABLE")

    # -- grid ---------------------------------------------------------
    print("\ngrid")
    payload, results, _o = grid.from_directory(root, today=AS_AT)
    check("15 cells", payload["summary"]["cells_total"], 15)
    check("13 available", payload["summary"]["cells_available"], 13)
    check("shortest wait", payload["summary"]["shortest_wait_days"], 55)
    check("date format declared", payload["date_format"], "YYYY-MM-DD")

    civ = payload["grid"][0]
    check("civil row", civ["matter"], "Civil")
    check("civil 2-day earliest", civ["cells"][0]["earliest_date"],
          "2027-03-22")
    check("civil 2-day count", civ["cells"][0]["dates_offered"], 90)
    check("6-15 civil is none, not missing", civ["cells"][3]["state"],
          "none")
    check("band assigned", civ["cells"][0]["band"], "months")

    c45 = civ["cells"][2]
    check("qualifier surfaces a later usable date",
          c45["earliest_unqualified_date"], "2027-10-18")
    check("and the gap is real",
          c45["unqualified_wait_days"] - c45["wait_days"], 76)

    mva = payload["grid"][2]
    check("mva 6-15 available where civil is not",
          mva["cells"][3]["state"], "available")

    print("\n%d passed, %d failed" % (len(PASS), len(FAIL)))
    return 1 if FAIL else 0


if __name__ == "__main__":
    sys.exit(main())
